export const KEY_AUTHORITIES = {
  WH_IMPORT: {
    SEARCH_MY_CREATE: 'WH_IMPORT_SEARCH_MY_CREATE',
    SEARCH_WAREHOUSE: 'WH_IMPORT_SEARCH_WAREHOUSE',
    CREATE: 'WH_IMPORT_CREATE',
    UPDATE_MY_CREATE: 'WH_IMPORT_UPDATE_MY_CREATE',
    UPDATE_WAREHOUSE: 'WH_IMPORT_UPDATE_WAREHOUSE',
    DELETE_MY_CREATE: 'WH_IMPORT_DELETE_MY_CREATE',
    DELETE_WAREHOUSE: 'WH_IMPORT_DELETE_WAREHOUSE',
  },

  WH_EXPORT: {
    SEARCH_MY_CREATE: 'WH_EXPORT_SEARCH_MY_CREATE',
    SEARCH_WAREHOUSE: 'WH_EXPORT_SEARCH_WAREHOUSE',
    CREATE: 'WH_EXPORT_CREATE',
    UPDATE_MY_CREATE: 'WH_EXPORT_UPDATE_MY_CREATE',
    UPDATE_WAREHOUSE: 'WH_EXPORT_UPDATE_WAREHOUSE',
    DELETE_MY_CREATE: 'WH_EXPORT_DELETE_MY_CREATE',
    DELETE_WAREHOUSE: 'WH_EXPORT_DELETE_WAREHOUSE',
  },

  WH_TRANSFER: {
    SEARCH_MY_CREATE: 'WH_TRANSFER_SEARCH_MY_CREATE',
    SEARCH_WAREHOUSE: 'WH_TRANSFER_SEARCH_WAREHOUSE',
    CREATE: 'WH_TRANSFER_CREATE',
    UPDATE_MY_CREATE: 'WH_TRANSFER_UPDATE_MY_CREATE',
    UPDATE_WAREHOUSE: 'WH_TRANSFER_UPDATE_WAREHOUSE',
    DELETE_MY_CREATE: 'WH_TRANSFER_DELETE_MY_CREATE',
    DELETE_WAREHOUSE: 'WH_TRANSFER_DELETE_WAREHOUSE',
  },

  WAREHOUSE: {
    WH_MAP: 'WH_MAP',
    WH_CARD: 'WH_CARD',
    WH_REPORT: 'WH_REPORT',
  },

  WH_ROOT: 'WH_ROOT',

  ROOT: 'ROLE_ROOT',
};
